# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "Adilhyz — Website"
baseURL = "http://localhost:1313"
# theme = ["FixIt", "shortcode-mmt-netease", "shortcode-sponsor-log"]
defaultContentLanguage = "id"
defaultContentLanguageInSubdir = false
disableLanguages = ["en", "zh-cn", "zh-TW","zh-HANT"]
hasCJKLanguage = false
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = false
buildDrafts = false
summaryLength = 150
titleCaseStyle = "ap"
capitalizeListTitles = false
timeZone = "Asia/Jakarta"
# the editor to use when creating new content
newContentEditor = "code"
# ignore some build errors
ignoreLogs = [
  "error-get-remote-image",
  "error-get-remote-json",
  "error-get-gh-repo",
  "error-remote-getjson",
  "error-missing-instagram-accesstoken",
  "warning-dev-version"
]

[outputs]
  home    = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term    = ["HTML", "RSS"]
  page = ["HTML", "RSS"]
