# -------------------------------------------------------------------------------------
# Multilingual and i18n | 多语言 i18n
# See: https://gohugo.io/content-management/multilingual/#configure-languages
# -------------------------------------------------------------------------------------

weight = 1
languageCode = "id"
languageName = "Indonesian"
hasCJKLanguage = false
copyright = "Karya ini dilisensikan di bawah Lisensi Creative Commons Attribution-NonCommercial 4.0 Internasional."
