# -------------------------------------------------------------------------------------
# Modules Configure
# See: https://gohugo.io/hugo-modules/configuration/#module-config-imports
# -------------------------------------------------------------------------------------

[[imports]]
  path = "github.com/hugo-fixit/fixit-bundle"
[[imports]]
  path = "github.com/hugo-fixit/shortcode-mmt-netease"
# ADD
[[imports]]
  path = "github.com/hugo-fixit/FixIt"
[[imports]]
  path = "github.com/hugo-fixit/shortcode-missing-translation"

[hugoVersion]
  extended = true
  min = "0.146.0"
