# -------------------------------------------------------------------------------------
# Permalinks Configuration
# See: https://gohugo.io/content-management/urls/#permalinks
# -------------------------------------------------------------------------------------

# posts = ":year/:month/:filename"
# private = ":sections[1:]/:slugorcontentbasename"
posts = "posts/:slugorcontentbasename"
