# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/theme-documentation-basics/#site-configuration
# -------------------------------------------------------------------------------------

# which hash function used for SRI, when empty, no SRI is used
# ("sha256", "sha384", "sha512", "md5")
# fingerprint = "sha256"

# Comment config
[page.comment]
  enable = true
  [page.comment.disqus]
    enable = true
    # Disqus shortname to use Disqus in posts
    shortname = "adilhyz"
    lazyLoad = true

# FixIt 0.3.10 | NEW Busuanzi count
[busuanzi]
  # whether to enable busuanzi count
  enable = true
  # busuanzi count core script source. Default is https://vercount.one/js
  source = "https://vercount.one/js"
  # whether to show the site views
  siteViews = false
  # whether to show the page views
  pageViews = false

# CDN config for third-party library files
[cdn]
  # CDN data file name, disabled by default ["jsdelivr.yml", "unpkg.yml", ...]
  # located in "themes/FixIt/assets/data/cdn/" directory
  # you can store your own data files in the same path under your project: "assets/data/cdn/"
  data = "unpkg.yml"

# FixIt 0.2.10 | NEW Analytics config
[analytics]
  enable = true
  [analytics.google]
    id = "G-32DSNF8QZY"
    # whether to anonymize IP
    anonymizeIP = true
  [analytics.umami]
    data_website_id = "40753570-2c69-4a05-8fb7-13f0b8163a58"
    src = "https://cloud.umami.is/script.js"
    data_host_url = ""
    data_domains = ""
