# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/theme-documentation-basics/#site-configuration
# -------------------------------------------------------------------------------------

# which hash function used for SRI, when empty, no SRI is used
# ("sha256", "sha384", "sha512", "md5")
# fingerprint = "sha256"

# Comment config
[page.comment]
  enable = false
  [page.comment.valine]
    enable = false
    appId = "7HwTRT0Q0Tfrat6ugrT6P67c-gzGzoHsz"
    appKey = "mhTY1kuUmviCtQwkwOASfsfD"
    # placeholder = "ヾﾉ≧∀≦)o~ 有事請留言！\n評論功能以郵件作為通知方式！\n如有必要請填寫正確郵箱哦！"
    placeholder = "ヾﾉ≧∀≦)o~ 有事请留言！\n评论功能以邮件作为通知方式！\n如有必要请填写正确邮箱哦！"
    avatar = "wavatar"
    meta = ['nick','mail','link']
    requiredFields = ['nick','mail','link']
    pageSize = 10
    lang = "zh-CN"
    visitor = false
    recordIP = false
    highlight = false
    enableQQ = false
    serverURLs = ""
    #  emoji data file name, default is "google.yml"
    # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
    # located in "themes/FixIt/assets/lib/valine/emoji/" directory
    # you can store your own data files in the same path under your project:
    # "assets/lib/valine/emoji/"
    emoji = ""
    commentCount = false # FixIt NEW | 0.2.13
  # FixIt 0.2.14 | NEW Giscus comments config (https://giscus.app/)
  [page.comment.giscus]
    enable = false
    repo = "Adilhyz/hugo-portfolio"
    repoId = "MDEwOlJlcG9zaXRvcnk0MDQzNDY3MDk="
    category = "General"
    categoryId = "DIC_kwDOGBnXVc4CApHL"
    mapping = "title"
    strict = "0" # FixIt NEW | 0.2.18
    term = ""
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "top" # ["top", "bottom"]
    lightTheme = "light"
    darkTheme = "dark_dimmed"
    lazyLoad = false

# FixIt 0.3.10 | NEW Busuanzi count
[busuanzi]
  # whether to enable busuanzi count
  enable = false
  # busuanzi count core script source. Default is https://vercount.one/js
  source = "https://vercount.one/js"
  # whether to show the site views
  siteViews = false
  # whether to show the page views
  pageViews = false

# CDN config for third-party library files
[cdn]
  # CDN data file name, disabled by default ["jsdelivr.yml", "unpkg.yml", ...]
  # located in "themes/FixIt/assets/data/cdn/" directory
  # you can store your own data files in the same path under your project: "assets/data/cdn/"
  data = "unpkg.yml"

# FixIt 0.2.10 | NEW Analytics config
[analytics]
  enable = true
  # My share URL: https://cloud.umami.is/share/FSPwm1IsrQFY7ZvP/lruihao.cn
  [analytics.umami]
    data_website_id = "40753570-2c69-4a05-8fb7-13f0b8163a58"
    src = "https://cloud.umami.is/script.js"
    data_host_url = ""
    data_domains = ""
